### ISSUE TITLE
cminwell 

### ISSUE THREAD

**Issue by agonzago** [FRBNY-DSGE/DSGE.jl#1]
Hi,
There is a small bug in the cminwell function in the DSGE package. Line 265 should be xh = x3 and not xh = h3. h3 is not defined in the code. I tried to make the change but I got other errors related to OptimizationTrace. 
 Andres

**Comment by pkofod** [comment]
What are the OptimizationTrace errors? Could be related to the latest tag of Optim.

**Comment by micahjsmith** [comment]
@pkofod Yes, it looks like we construct an `OptimizationTrace` object via a deprecated syntax at https://github.com/FRBNY-DSGE/DSGE.jl/blob/master/src/estimate/csminwel.jl#L122.

@agonzago You could confirm that your change works by downgrading your Optim.jl version to 0.4.5 until we have a fix for that separate issue.

**Comment by micahjsmith** [comment]
@agonzago Please try to checkout the master branch (`Pkg.checkout("DSGE")`) which should fix the issue with Optim.

**Comment by pkofod** [comment]
Good to see it resolved. I made the change because it allows for custom printing based on dispatch on the `Optimizer` type. For example, it makes no sense to write a gradient norm in Nelder-Mead and so on. So you can do something like https://github.com/JuliaOpt/Optim.jl/blob/master/src/nelder_mead.jl#L59 if you have "custom" information you want to show (noticed I changed the gradient norm to the convergence criterior for NM).

**Comment by micahjsmith** [comment]
Closed by 732169ab86c8e4a99d2442f1ec32dfd0ac5b84b2
