### ISSUE TITLE
Is it possible to update Performance Comparison?

### ISSUE THREAD

**Issue by Moelf** [FRBNY-DSGE/DSGE.jl#154]
https://frbny-dsge.github.io/DSGE.jl/stable/julia_forecasting/#Performance-Improvements-1

it shouldn't be too hard to compare the same DSGE code with Julia 0.4.5 and 1.7? (without digging up MATLAB again, well, the assumption being MATLAB didn't get visibly faster)

**Comment by ShlokG** [comment]
Hi Jerry,

Thanks for your question! We can certainly do so. Is there a particular reason you have in mind for this comparison? It was useful to us last time around because we were deciding whether to switch our code from MATLAB to Julia but we are not currently contemplating a switch back. 

Regards, 
Shlok

**Comment by Moelf** [comment]
oh, nothing really, just want to see if there's visible free speedup from Julia 0.4.5 -> 1.7
