### ISSUE TITLE
gensys

### ISSUE THREAD

**Issue by matthieugomez** [FRBNY-DSGE/DSGE.jl#2]
I have rewritten the `gensys` function in Julia [here](https://github.com/matthieugomez/Gensys.jl/blob/master/src/Gensys.jl). Compared to the version in this repository, the version is faster (some operations are done in place) and clearer (no unecessary diag/diagm conversion or Float64/Int). 
There is also a design change. In my version, the function `gensys` does not throws errors  in case of non unicity or non uniqueness since one may be still interested in the results in these cases. This is the main reason that I needed to rewrite gensys.jl to begin with.

If you're interested, I can write a pull request to replace the gensys file in this repository by the modified one. The only other change would be to throw an error in `solve` rather than `gensys` in case of non uniqueness/non existence.

**Comment by emoszkowski** [comment]
@mattheiugomez, thanks for opening the issue - this looks great. @pearlzli, can you and @abhig94 check that our tests still pass using Gensys.jl?

**Comment by pearlzli** [comment]
Hi @matthieugomez, thanks so much for doing this! Could you please submit a pull request to DSGE.jl, as you suggested?

@abhig94 and I ran our tests on Gensys.jl, and they pass after changing calls to `A_mul_Bt` and `At_mul_B` to `A_mul_Bc` and `Ac_mul_B` (transposes to conjugate transposes, since we do complex Schur decompositions in `gensys`) respectively.

**Comment by pearlzli** [comment]
Closed with #3 - thanks again!
