### ISSUE TITLE
ERROR: UndefVarError: Model1002 not defined

### ISSUE THREAD

**Issue by YehandAldo** [FRBNY-DSGE/DSGE.jl#29]
Hello

I am trying to run make_packet.jl in JuliaPro_v1.0.5-2 but I am getting 

`ERROR: UndefVarError: Model1002 not defined`

after run line of `m = Model1002() `

What could I be do wrong?

Thanks  a lot

**Comment by chenwilliam77** [comment]
Hi there,

Which version of the DSGE package do you have, and what version of Julia are you using? And how are you running make_packet.jl? When I run the script on my version of the master branch, I do not get that error and can successfully create Model1002.

Best,

William

**Comment by YehandAldo** [comment]
Thanks a lot for the answer dear William

I was running in JuliaPro_v1.0.5-2 but I uninstalled it. 
Now the version of Julia I am using is 1.0.5
and the version of the DSGE package is v0.8.1

Now, when I run_default.jl I get

`UndefVarError: Setting not defined`

what is the same when I run make_packet.jl

Thanks

Aldo

**Comment by chenwilliam77** [comment]
You should upgrade to DSGE v1.0.0. We have broken out parts of the DSGE.jl package into a separate package called ModelConstructors.jl, which consequently meant some of our older examples scripts no longer work. All example scripts in v1.0.0 should work.

Best,

William

**Comment by YehandAldo** [comment]
Thanks a lot dear William

I am using  `add DSGE@v1.0.0` in order to upgrade, but I get 

```
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DSGE [6cf23378]:
 DSGE [6cf23378] log:
 ├─possible versions are: [0.5.0-0.5.1, 0.6.0, 0.7.0-0.7.2, 0.8.0-0.8.1] or uninstalled
 └─restricted to versions 1.0.0 by an explicit requirement — no versions left
```

Am I using a correct way to upgrade DSGE?

Aldo

**Comment by chenwilliam77** [comment]
Try these suggestions (in particular, try upgrading rather than adding): https://discourse.julialang.org/t/pkg-unsatisfiable-requirements-detected/22269/7

**Comment by YehandAldo** [comment]
Thanks a lot dear William

I think I was wrong setting the path

Since initially run_default.jl was in `".../.julia/packages/DSGE/R18NA/docs/examples"` I was running
`include (".../.julia/packages/DSGE/R18NA/docs/examples/run_default.jl")`. 

But after deleting and updating DSGE to version 1.0.0 run_default.jl is in 
`"... /. julia/dev/DSGE/docs/examples/run_default.jl`
therefore now I'm executing 
`include ("... /. julia/dev/DSGE/docs/examples/run_default.jl")`

and It works until 

`df = load_data(m, try_disk = false, check_empty_columns = false, summary_statistics = :none)
`

where I get an error message


```
Creating dataset...
API key loaded.
Fetching FRED series GDP...
HTTP.ExceptionRequest.StatusError(400, "GET", "/fred/series/observations?api_key=0123456789abcdef0123456789abcdef&observation_start=1959-01-01&series_id=GDP&observation_end=2018-09-30&vintage_dates=2018-11-15&file_type=json&frequency=q", HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Content-Length: 187
Server: Apache
Vary: User-Agent
Date: Wed, 04 Dec 2019 21:40:15 GMT
Connection: keep-alive

{"error_code":400,"error_message":"Bad Request.  The value for variable api_key is not registered.  Read https:\/\/research.stlouisfed.org\/docs\/api\/api_key.html for more information."}""")┌ Warning: FRED series GDP could not be fetched at vintage 181115.
└ @ DSGE C:\Users\Aldo\.julia\dev\DSGE\src\data\fred_data.jl:96
Fetching FRED series GDP without vintage...
HTTP.ExceptionRequest.StatusError(400, "GET", "/fred/series/observations?api_key=0123456789abcdef0123456789abcdef&observation_start=1959-01-01&series_id=GDP&observation_end=2018-09-30&file_type=json&frequency=q", HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Content-Length: 187
Server: Apache
Vary: User-Agent
Date: Wed, 04 Dec 2019 21:40:17 GMT
Connection: keep-alive
```
....
```

{"error_code":400,"error_message":"Bad Request.  The value for variable api_key is not registered.  Read https:\/\/research.stlouisfed.org\/docs\/api\/api_key.html for more information."}""")┌ Warning: FRED series GDI could not be fetched.
└ @ DSGE C:\Users\Aldo\.julia\dev\DSGE\src\data\fred_data.jl:109
Updated data from FRED written to C:\Users\Aldo\.julia\dev\DSGE\save\input_data\raw\fred_181115.csv.
ERROR: LoadError: ArgumentError: column name :GDP not found in the data frame

```

Could you please give me suggestions how to fix this?

Aldo

**Comment by chenwilliam77** [comment]
Try https://frbny-dsge.github.io/DSGE.jl/latest/input_data/#Setup-1. You might be missing the Fred API key.

**Comment by YehandAldo** [comment]
Dear William

Thanks a lot for your suggestions, now it works.

I requested an API key and I made it be accessible to FredData by using

`julia> Pkg.add("FredData")`

```
julia> open(joinpath(homedir(), ".freddatarc"), "w") do f
           write(f, "0123456789abcdef0123456789abcdef")
       end
```

Thanks again

Aldo

**Comment by TeshomeBTule** [comment]
> You should upgrade to DSGE v1.0.0. We have broken out parts of the DSGE.jl package into a separate package called ModelConstructors.jl, which consequently meant some of our older examples scripts no longer work. All example scripts in v1.0.0 should work.
> 
> Best,
> 
> William

I am using Julia v1.9.0 and DSGE v1.3.0 but the same error appears i.e. ERROR: UndefVarError: Model1002 not defined.
In my case, the issue extends to JLD2. That means when I run 'using DSGE' , the errors:
1. ERROR: LoadError: type DataType has no field size 
2. ERROR: LoadError: Failed to precompile JLD2 [033835bb-8acc-5ee8-8aae-3f567f8a3819] to "/home/teshe/.julia/compiled/v1.9/JLD2/jl_1ioPDr". 

When I re-run 'using DSGE' , the error disappears but at the instantiate step, i.e. at
m = Model1002("ss10") 
I face this error ==> ERROR: UndefVarError: `Model1002` not defined 

The error related to JLD2 looks the following:

julia> using DSGE
[ Info: Precompiling DSGE [6cf23378-2c47-544c-b0c3-6efefe57ca11]
[ Info: Skipping precompilation since __precompile__(false). Importing DSGE [6cf23378-2c47-544c-b0c3-6efefe57ca11].
[ Info: Precompiling ModelConstructors [e47e5152-bd14-11e9-1b46-c951f0a7041d]
[ Info: Skipping precompilation since __precompile__(false). Importing ModelConstructors [e47e5152-bd14-11e9-1b46-c951f0a7041d].
WARNING: method definition for test_matrix_eq2 at /home/teshe/.julia/packages/ModelConstructors/r0PZ3/src/util.jl:163 declares type variable T but does not use it.
[ Info: Precompiling SMC [c6043b28-c053-11e9-348c-19d3cb73bbb3]
[ Info: Skipping precompilation since __precompile__(false). Importing SMC [c6043b28-c053-11e9-348c-19d3cb73bbb3].
[ Info: Precompiling JLD2 [033835bb-8acc-5ee8-8aae-3f567f8a3819]
ERROR: LoadError: type DataType has no field size
Stacktrace:
 [1] getproperty(x::Type, f::Symbol)
   @ Base ./Base.jl:32
 [2] top-level scope
   @ ~/.julia/packages/JLD2/AwnKI/src/data.jl:598
 [3] include(mod::Module, _path::String)
   @ Base ./Base.jl:457
 [4] include(x::String)
   @ JLD2 ~/.julia/packages/JLD2/AwnKI/src/JLD2.jl:1
 [5] top-level scope
   @ ~/.julia/packages/JLD2/AwnKI/src/JLD2.jl:442
 [6] include
   @ ./Base.jl:457 [inlined]
 [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
   @ Base ./loading.jl:2010
 [8] top-level scope
   @ stdin:2
in expression starting at /home/teshe/.julia/packages/JLD2/AwnKI/src/data.jl:597
in expression starting at /home/teshe/.julia/packages/JLD2/AwnKI/src/JLD2.jl:1
in expression starting at stdin:2
ERROR: LoadError: Failed to precompile JLD2 [033835bb-8acc-5ee8-8aae-3f567f8a3819] to "/home/teshe/.julia/compiled/v1.9/JLD2/jl_1ioPDr".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2260
  [3] compilecache
    @ ./loading.jl:2127 [inlined]
  [4] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1770
  [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1625
  [6] macro expansion
    @ ./loading.jl:1613 [inlined]
  [7] macro expansion
    @ ./lock.jl:267 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1576
  [9] include
    @ ./Base.jl:457 [inlined]
 [10] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1801
 [11] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1625
 [12] macro expansion
    @ ./loading.jl:1613 [inlined]
 [13] macro expansion
    @ ./lock.jl:267 [inlined]
 [14] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1576
 [15] include
    @ ./Base.jl:457 [inlined]
 [16] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1801
 [17] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1625
 [18] macro expansion
    @ ./loading.jl:1613 [inlined]
 [19] macro expansion
    @ ./lock.jl:267 [inlined]
 [20] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1576
in expression starting at /home/teshe/.julia/packages/SMC/LDbms/src/SMC.jl:3
in expression starting at /home/teshe/.julia/packages/DSGE/fjU1P/src/DSGE.jl:3
